name: airsim
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - idna==3.4
    - msgpack-python==0.5.6
    - msgpack-rpc-python==0.4.1
    - numpy==1.24.2
    - opencv-contrib-python==4.7.0.68
    - tornado==4.5.3
    - urllib3==1.26.14
    - opencv-python==4.10.0.84
    - torch==2.5.1
    - fastdtw==0.3.4
    - matplotlib==3.9.1
